/**
 *
 * Copyright: Copyright (c) 2020 by AQUENT, L.L.C.
 * Company: AQUENT, L.L.C.
 * @created 08-09-2020
 *
 * Application level properties will be here..
 *
 */
const Properties = {
  Welcome_text: "Welcome",
  Project_name: "Project Name",
  Campaign_name: "Campaign Name",
  Email_label: "Email",
  Password_text_label: "Password",
  API_key_label: "API key",
  Enter_account_name: "Enter Your Account Name:",
  Next_text: "Next",
  Enter_emailaddress_password: "Enter Your Email Address And Password:",
  Log_in_label: "Log In",
  Enter_api_key_label: "Enter Your API Key:",
  Email_address_label: "Enter email address",
  Password_label: "Enter password",
  Key_label: "Enter your api key",
  Account_name_label: "Account name",
  Account_url_error: "Please enter account url",
  Valid_Account_name_error: "Please enter valid account name",
  Valid_account_url_error: "Please enter valid account url",
  Valid_email_address_error: "Please enter a valid email",
  Api_key_error: "Please enter Api key",
  Api_valid_key_error: "Please enter valid Api key",
  ArtBoard_not_selected_error: "An artboard must be created to export.",
  Password_error: "Please enter password",
  User_not_found_error: "User not found. Please try again",
  Logout_message: "Logged out successfully",
  Logout_label: "Logout",
  Refresh_project_label: "Refresh project list",
  Refresh_campaign_label: "Refresh campaign list",
  Export_file_to_robohead_label: "EXPORT FILE TO",
  Export_file_from_robohead_label: "EXPORT FILE FROM",
  Enter_search_project_text: "Enter project name",
  Enter_search_campaign_text: "Enter campaign name",
  Grid_emptyText: "No records to display.",
  File_name_label: "File Name",
  Enter_file_name_label: "Enter file name",
  Project_label: "Project",
  Campaign_label: "Campaign",
  Library_label: "Library",
  Format_label: "Format:",
  PNG_label: "PNG",
  SVG_label: "SVG",
  PDF_label: "PDF",
  JPG_label: "JPG",
  Export_label: "Export",
  Open_label: "Open",
  Project_header_label: "PROJECT",
  Campaign_header_label: "CAMPAIGN",
  Enter_file_name: "Please enter file name",
  Campaign_select_label: "Please select campaign",
  Project_select_label: "Please select project",
  Folder_select_label: "Please select Folder",
  File_select_label: "Please select file",
  Label_go_to_robohead_account: "Go to my RoboHead account",
  Label_get_help: "Online Help",
  Label_send_feedback: "Submit Suggestion",
  Add_new_version: "Add New Version",
  Cancel_button: "Cancel",
  Please_select_object_error_label:
    "Please select atleast one object from XD document.",
  File_upload_progress_label: "File upload in progress.",
  File_saved_message: "File has been saved.",
  File_download_message: "File has been downloaded successfully.",
  Select_file_label: "Select File:",
  Bad_credentails_message: "Email address or password not recognized.",
  XD_enable_error_message:
    "XD Plugin is not enabled for your account. Please contact Robohead Support.",
  All_open_work_enable_error:
    "Tasks, Reviews, and To-Do's are not enabled in your account. Please contact Robohead Support.",
  Connect_to_internet_label: "Connect to the Internet",
  Internet_connection_error_message:
    "In order to function correctly, this plugin requires access to the Internet. Please connect to a network that has Internet access.",
  My_work_label: "MY WORK",
  All_open_worklabel: "All Open Work",
  Refresh_label: "Refresh",
  Filter_by_label: "Filter By",
  Setting_label: "Settings",
  Sort_label: "Sort",
  Expand_label: "Expand",
  Collapse_label: "Collapse",
  Task_label: "Task",
  Due_date_label: "Due Date",
  To_do_label: "To-Do",
  Created_on_label: "Created On",
  Description_label: "Description",
  Review_label: "Review",
  Project_formattedNumber_label: "Project #",
  View_details_label: "View Details",
  Sort_by_label: "Sort By",
  Apply_label: "Apply",
  Show_label: "Show",
  Client_label: "Client",
  Project_status_label: "Project Status",
  Campaign_label: "Campaign",
  Campaign_number_label: "Campaign #",
  Start_date_label: "Start Date",
  Review_status_label: "Review Status",
  Assignees_label: "Assignee(s)",
  Created_by_label: "Created By",
  Modified_by_label: "Modified By",
  Predeccessors_label: "Predecessor(s)",
  Successors_label: "Successor(s)",
  Duration_label: "Duration",
  Estimated_hours_label: "Estimated Hours",
  Hours_worked_label: "Hours Worked",
  Review_owner_label: "Review Owner(s)",
  Review_type_label: "Review Type",
  Stages_label: "# of Stages",
  Comments_label: "Comments",
  Notes_label: "Notes",
  Current_stage_name: "Current Stage Name",
  Current_stage_due_date: "Current Stage Due Date",
  Enter_todo_name_label: "Please enter To-Do name",
  Valid_days_error_message: "Please enter valid days",
  Valid_month_error_message: "Please enter valid month",
  Valid_year_error_message: "Please enter valid year",
  Valid_date_error_message: "Please enter valid date",
  Is_ToDo_ocmplete_label: "Is To-Do complete?",
  Add_description_label: "Add Description",
  To_Do_description: "To-Do Description",
  Enter_todo_date_label: "Enter To-Do name...",
  To_do_name_label: "To-Do Name",
  Tags_label: "Tags",
  Year_label: "YYYY",
  Month_label: "MM",
  Day_label: "DD",
  Modify_ToDo_label: "Modify To-Do",
  Task_ID_label: "Task ID",
  Task_group_label: "Task Group",
  Task_role_label: "Task Role",
};
module.exports = Properties;
